# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ramblings on Code
email: damian@openmama.org
description: > # this means to ignore newlines until "baseurl:"
  General ramblings and musings of a some time code monkey.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dmagOM.github.io" # the base hostname & protocol for your site
twitter_username: twistedpotato
github_username:  dmagOM

# Build settings
markdown: kramdown
